SMOTE:
  random_state: 0
train_test_split:
  test_size: .3
  random_state: 0
LogisticRegression:
  random_state: 0
  solver: 'lbfgs'
  multi_class: 'ovr'
  max_iter: 10000
RandomForestClassifier:
  n_estimators: 100
  random_state: 0